version: '3'

networks:
  credit_network:
    driver: bridge

services:
  credit-rating-engine:
    hostname: credit-rating-engine
    container_name: credit-rating-engine
    build: .
    links:
      - fluentd
    volumes:
      - ./webservice:/webservice
    ports:
      - "5000:5000"
    networks:
      - credit_network
    command: ["gunicorn", "--log-config", "/logging.conf", "-b", "0.0.0.0:5000", "-w", "4", "webservice.wsgi:app"]
    logging:
      driver: "json-file"
      options:
            max-size: 100m
            max-file: "5"

  fluentd:
    container_name: fluentd
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    expose:
      - 24224
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - credit_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    hostname: elasticsearch
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "cluster.name=docker-cluster"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
    networks:
      - credit_network

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    container_name: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    networks:
      - credit_network

volumes:
  elasticdata:
    driver: local